### ISSUE TITLE
1.10.2 Startup Crash

### ISSUE THREAD

**Issue by JonL98** [ata4/dragon-mounts#33]
DragonMounts seems to have an issue with Forge 1.10.2-12.18.2.2099. I believe the conflict is caused by the naming convention of the dragon egg in the bolded lines. The requirements must have changed in Forge for its block registry. I'm not certain I'm explaining this accurately since I'm not very familiar with the Forge libraries involved in this.

---- Minecraft Crash Report ----
WARNING: coremods are present:
Contact their authors BEFORE contacting forge
// I let you down. Sorry :(
Time: 10/20/16 6:33 PM
XRay version: 33
Description: Initializing game
java.lang.ArrayIndexOutOfBoundsException: 16
at net.minecraftforge.fml.common.registry.GameData$BlockCallbacks.onAdd(GameData.java:303)
at net.minecraftforge.fml.common.registry.GameData$BlockCallbacks.onAdd(GameData.java:284)
at net.minecraftforge.fml.common.registry.FMLControlledNamespacedRegistry.addObjectRaw(FMLControlledNamespacedRegistry.java:586)
at net.minecraftforge.fml.common.registry.FMLControlledNamespacedRegistry.add(FMLControlledNamespacedRegistry.java:484)
at net.minecraftforge.fml.common.registry.FMLControlledNamespacedRegistry.register(FMLControlledNamespacedRegistry.java:831)
at net.minecraftforge.fml.common.registry.GameData.register_impl(GameData.java:254)
at net.minecraftforge.fml.common.registry.GameRegistry.register(GameRegistry.java:153)
**at info.ata4.minecraft.dragon.server.CommonProxy.onPreInit(CommonProxy.java:41)
at info.ata4.minecraft.dragon.client.ClientProxy.onPreInit(ClientProxy.java:37)
at info.ata4.minecraft.dragon.DragonMounts.onPreInit(DragonMounts.java:64)**
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:597)
at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239)
at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:609)
at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:257)
at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
at net.minecraft.client.main.Main.main(SourceFile:124)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
-- Head --
Thread: Client thread
Stacktrace:
at net.minecraftforge.fml.common.registry.GameData$BlockCallbacks.onAdd(GameData.java:303)
at net.minecraftforge.fml.common.registry.GameData$BlockCallbacks.onAdd(GameData.java:284)
at net.minecraftforge.fml.common.registry.FMLControlledNamespacedRegistry.addObjectRaw(FMLControlledNamespacedRegistry.java:586)
at net.minecraftforge.fml.common.registry.FMLControlledNamespacedRegistry.add(FMLControlledNamespacedRegistry.java:484)
at net.minecraftforge.fml.common.registry.FMLControlledNamespacedRegistry.register(FMLControlledNamespacedRegistry.java:831)
at net.minecraftforge.fml.common.registry.GameData.register_impl(GameData.java:254)
at net.minecraftforge.fml.common.registry.GameRegistry.register(GameRegistry.java:153)
at info.ata4.minecraft.dragon.server.CommonProxy.onPreInit(CommonProxy.java:41)
at info.ata4.minecraft.dragon.client.ClientProxy.onPreInit(ClientProxy.java:37)
at info.ata4.minecraft.dragon.DragonMounts.onPreInit(DragonMounts.java:64)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:597)
at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239)
at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
at com.google.common.eventbus.EventBus.post(EventBus.java:275)
at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:609)
at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:257)
at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
-- Initialization --
Details:
Stacktrace:
at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
at net.minecraft.client.main.Main.main(SourceFile:124)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:483)
at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
-- System Details --
Details:
Minecraft Version: 1.10.2
Operating System: Windows 10 (amd64) version 10.0
Java Version: 1.8.0_25, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 164573208 bytes (156 MB) / 420413440 bytes (400 MB) up to 8576565248 bytes (8179 MB)
JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
FML: Minecraft 1.10.2 MCP 9.32 Powered by Forge 12.18.2.2099 Optifine OptiFine_1.10.2_HD_U_C1 14 mods loaded, 14 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
UCH mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
UCH FML{8.0.99.99} [Forge Mod Loader](forge-1.10.2-12.18.2.2099.jar) 
UCH Forge{12.18.2.2099} [Minecraft Forge](forge-1.10.2-12.18.2.2099.jar) 
UCH tntmod{1.7.10} [TNTmod]([1.10.2]TNTMod.jar) 
UCH thedragonlib{1.10.2-1.0.3.0} [TheDragonLib](thedragonlib-1.10.2-1.0.3.0.jar) 
UCH armorplus{1.10.2-7.0.1.1.6} [ArmorPlus](armorplus-1.10.2-7.0.1.1.6.jar) 
UCH customnpcs{1.9.0_beta} [CustomNPCs](CustomNPCs_1.10.2_beta%2820oct16%29.jar) 
UCH examplemod{1.0} [examplemod](DragonMounts-1.10.2X.jar) 
UCE DragonMounts{@VERSION@} [Dragon Mounts](DragonMounts-1.10.2X.jar) 
UCH LunatriusCore{1.1.2.36} [LunatriusCore](LunatriusCore-1.10.2-1.1.2.36-universal.jar) 
UCH Roguelike{1.5.4} [Roguelike Dungeons](RoguelikeDungeons-1.10.2-1.5.4.jar) 
UCH RTG{1.9.4} [Realistic Terrain Generation](RTG-1.10.2-2.0.0-alpha.6.jar) 
UCH Schematica{1.7.8.152} [Schematica](Schematica-1.10.2-1.7.8.152-universal.jar) 
UCH worldedit{6.1.3} [WorldEdit](worldedit-forge-mc1.9.4-6.1.3-dist.jar) 
Loaded coremods (and transformers): 
GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 373.06' Renderer: 'GeForce GT 430/PCIe/SSE2'
Launched Version: 1.10.2
LWJGL: 2.9.4
OpenGL: GeForce GT 430/PCIe/SSE2 GL version 4.5.0 NVIDIA 373.06, NVIDIA Corporation
GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.
Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: 
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: 2x Pentium(R) Dual-Core CPU E5700 @ 3.00GHz
OptiFine Version: OptiFine_1.10.2_HD_U_C1
Render Distance Chunks: 10
Mipmaps: 4
Anisotropic Filtering: 16
Antialiasing: 8
Multitexture: true
Shaders: null
OpenGlVersion: 4.5.0 NVIDIA 373.06
OpenGlRenderer: GeForce GT 430/PCIe/SSE2
OpenGlVendor: NVIDIA Corporation
CpuCount: 2

**Comment by ata4** [comment]
Yeah, that doesn't look good. Do older versions of Forge for 1.10.2 still work? If so, then there really must have been some internal changes.

**Comment by JonL98** [comment]
Some, yes, but I'm not sure what version these changes were made. If you want to take a look at the recent changes in FMLControlledNamespacedRegistry, you can find it [here](https://github.com/MinecraftForge/MinecraftForge/commits/1.10.x/src/main/java/net/minecraftforge/fml/common/registry/FMLControlledNamespacedRegistry.java). I looked through it some, but I just don't know enough of the code to understand it.

**Comment by ata4** [comment]
I recompiled the mod with the latest Forge version and it seems to work fine with 12.18.2.2099.

The stacktrace is a bit weird, though. In that line, I'm not even using `GameRegistry.register()` anymore, since it's deprecated. Are you sure you have the latest version? I can't really tell, because `@VERSION@` wasn't replaced properly in your build for some reason.

**Comment by JonL98** [comment]
I compiled it with 12.18.2.2099 as well, since I've been adding my own dragons. The only code that's not up to date was the "Update to 1.10.2" commit which changed the method "getBiomeGenForCoords()" to "getBiome()" in a few of the breed classes and DragonBreedHelper. I intentionally didn't update that because it caused compiling to fail for 12.18.2.2099.

**Comment by JonL98** [comment]
This is due to too many metadatas for the egg block because I added breeds. Apparently, metadata is limited to 0-15.
